spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
  security:
    jwt:
      secret-key: ${SECRET_KEY}
    oauth2:
      client:
        registration:
          naver:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9000/naver/callback

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  data:
    redis:
      host: localhost
      port: 6369
      database: 0
server:
  port: 9000

naver:
  auth-url: "https://nid.naver.com"
  api-url: "https://openapi.naver.com"
#
#
#  spring:
#    datasource:
#      username: ${DB_USERNAME}
#      password: ${DB_PASSWORD}
#      url: ${DB_URL}
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      properties:
#        hibernate:
#          show_sql: true
#          format_sql: true
#          use_sql_comments: true
#          hbm2ddl:
#            auto: update
#    security:
#      jwt:
#        secret-key: ${SECRET_KEY}
#
#      oauth2:
#        naver:
#          client-id: ${CLIENT_ID}
#          secret: ${CLIENT_SECRET}
#          url:
#            auth: https://nid.naver.com
#            api: https://openapi.naver.com
#    data:
#      redis:
#        host: localhost
#        port: 6369
#        database: 0
#
#  server:
#    port: 9000