spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    jwt:
      secret-key: ${SECRET_KEY}
    oauth2:
      client:
        registration:
          naver:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - email
              - name
              - phone
              - profile_image
              - gender
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${BASE_LOGIN_URL}  # 기본 redirect-url

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  data:
    redis:
      host: localhost # 도메인 구매 시 변경 예정
      port: 6379
      database: 1
      
server:
  port: 9000

logging:
  level:
    org:
      hibernate:
        type : trace

default:
  login:
    redirect:
      url: ${LOGIN_URL}
